apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: exam-miesvandenberghe
  labels:
    createdBy: "Mies-VandenBerghe"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: mies022/api
          imagePullPolicy: Always
          name: api-demo
          ports:
            - containerPort: 80
          env:
            - name: NAME
              value: "YourNameHere"
            - name: DATE
              value: "2024-05-10"  # Example date, change as needed
          resources: {}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10


--- 
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: exam-miesvandenberghe
spec:
  type: NodePort
  selector:
    app: api  # Updated to match the corrected deployment labels
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30001

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api  # Updated to match the corrected deployment labels
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

