apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: exam-miesvandenberghe
  labels:
    createdBy: "Mies-VandenBerghe"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-demo
          image: mies022/frontend
          imagePullPolicy: Always
          env:
            - name: API_HOST
              value: "api-service"  # Assuming 'api-service' is the name of your API service in Kubernetes
            - name: API_PORT
              value: "80"  # Assuming your API service is exposed on port 80
          ports:
            - containerPort: 80
          resources: {}

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - k3d-k3s-default-agent-2

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend  # Changed from 'app' to 'frontend' to match the corrected pod labels
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
