version: '3.9'


services:
  web:
    build: ./pointsApp
    image: mies/part1
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://student:examen@db:5432/points
    networks:
      - web
      - database
    depends_on:
      db:
        condition: service_healthy

  db:
    image: ghcr.io/eslih/postgres:16.1-alpine
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres:/var/lib/postgresql/data/
    networks:
      - database


volumes:
  postgres:

networks:
  web:
  database:



